## catalog of libraries and plugins used to build the Archer-Game-Template2 project

[versions]

jme = "3.10.0-alpha1"

[libraries]

groovy-jsr223 = "org.apache.groovy:groovy-jsr223:5.0.4"
heart = "com.github.stephengold:Heart:9.3.0"

jme3-awt-dialogs = { module = "org.jmonkeyengine:jme3-awt-dialogs", version.ref = "jme" }
jme3-core = { module = "org.jmonkeyengine:jme3-core", version.ref = "jme" }
jme3-desktop = { module = "org.jmonkeyengine:jme3-desktop", version.ref = "jme" }
jme3-effects = { module = "org.jmonkeyengine:jme3-effects", version.ref = "jme" }
jme3-jogg = { module = "org.jmonkeyengine:jme3-jogg", version.ref = "jme" }
jme3-lwjgl3 = { module = "org.jmonkeyengine:jme3-lwjgl3", version.ref = "jme" }
jme3-plugins = { module = "org.jmonkeyengine:jme3-plugins", version.ref = "jme" }
jme3-testdata = { module = "org.jmonkeyengine:jme3-testdata", version.ref = "jme" }

lemur = "com.simsilica:lemur:1.16.0"
lemur-props = "com.simsilica:lemur-props:1.2.0"
lemur-proto = "com.simsilica:lemur-proto:1.13.0"

minie = "com.github.stephengold:Minie:9.0.3"
skyControl = "com.github.stephengold:SkyControl:1.1.0"

[bundles]

[plugins]
